### ISSUE TITLE
مشکل پوشه با فایربیس

### ISSUE THREAD

**Issue by Hoss3inf** [pusheco/android-studio-sample#21]
هنگام اجرای برنامه، مرتبا این پیغام رو دریافت می کنم. سرویس پوش هم کار نمی کند. لطفا راهنمایی کنید:
```
2020-01-04 12:38:37.440 17171-17786/com.example.app E/Pushe: Sending upstream message failed
co.ronash.pushe.a: Initializing Firebase Messaging failed
        at co.ronash.pushe.Pushe.a(Unknown Source)
        at co.ronash.pushe.Pushe.a(Unknown Source)
        at co.ronash.pushe.h.d.b(Unknown Source)
        at co.ronash.pushe.task.tasks.d.a(Unknown Source)
        at co.ronash.pushe.task.e.a(Unknown Source)
        at co.ronash.pushe.task.b.a.a.onRunJob(Unknown Source)
        at com.evernote.android.job.Job.runJob(Job.java:124)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:181)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:166)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:149)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.lang.NoSuchMethodException: <init> [class com.google.firebase.iid.FirebaseInstanceId]
        at java.lang.Class.getConstructor0(Class.java:2204)
        at java.lang.Class.getDeclaredConstructor(Class.java:2050)
        at co.ronash.pushe.Pushe.a(Unknown Source) 
        at co.ronash.pushe.Pushe.a(Unknown Source) 
        at co.ronash.pushe.h.d.b(Unknown Source) 
        at co.ronash.pushe.task.tasks.d.a(Unknown Source) 
        at co.ronash.pushe.task.e.a(Unknown Source) 
        at co.ronash.pushe.task.b.a.a.onRunJob(Unknown Source) 
        at com.evernote.android.job.Job.runJob(Job.java:124) 
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:181) 
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:166) 
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:149) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:762) 
```

**Comment by fsghasemi** [comment]
سلام کدوم ورژن پوشه رو استفاده میکنید؟

**Comment by mahdi-malv** [comment]
Issue closed due to inactivity for 14 days
