### ISSUE TITLE
The meta-data tag in your app's AndroidManifest.xml does not have the right value

### ISSUE THREAD

**Issue by maysamrasoli** [pusheco/android-studio-sample#3]
با سلام
طبق راهنمای ارایه شده پیش رفتم با خطای زیر برخورد کردم.
از آخرین نسخه ارایه شده استفاده کردم.
با تشکر

  java.lang.RuntimeException: Unable to start activity : java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 9452000 but found 4242000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                           Caused by: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 9452000 but found 4242000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
                                                              at com.google.android.gms.common.zze.zzbs(Unknown Source)
                                                              at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
                                                              at com.google.android.gms.common.zzc.isGooglePlayServicesAvailable(Unknown Source)
                                                              at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
                                                              at co.ronash.pushe.log.handlers.SentryHandler.getTags(Unknown Source)
                                                              at co.ronash.pushe.log.handlers.SentryHandler.onLog(Unknown Source)
                                                              at co.ronash.pushe.log.g.g(Unknown Source)
                                                              at co.ronash.pushe.log.g.e(Unknown Source)
                                                              at co.ronash.pushe.log.g.b(Unknown Source)
                                                              at co.ronash.pushe.Pushe.initialize(Unknown Source)
                                                              at ir.category_manager.MindMapActivity.onCreate(MindMapActivity.java:60)
                                                              at android.app.Activity.performCreate(Activity.java:6237)
                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                              at android.os.Looper.loop(Looper.java:148) 
                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                              at java.lang.reflect.Method.invoke(Native Method)

**Comment by akramShokri** [comment]
سلام
خطای فوق به معنای این هست که نسخه ی کتابخانه ی گوگل پلی که استفاده کرده اید نسخه ی قدیمی است. 
لطفا محتوای فایل
build.gradle 
خود را برای ما بفرستید تا در پیدا کردن علت مشکل شما را راهنمایی کنیم..
بهتر است برای این منظور به پشتیبانی پوشه ایمیل بزنید.

**Comment by maysamrasoli** [comment]
خیلی ممنون


apply plugin: 'com.android.application'

android {

    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "ir.category_manager"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile project(':pushe-lib-1.2.0')
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:25.1.1'
    compile 'com.android.support:support-v4:25.1.1'
    compile 'com.android.support:design:25.1.1'
    compile 'com.android.support:design:25.1.1'
    compile 'com.intuit.sdp:sdp-android:1.0.3'
    compile 'com.github.clans:fab:1.6.4'
    compile 'com.google.android.gms:play-services-gcm:9.4.0'
    compile 'com.google.code.gson:gson:2.8.0'


}

**Comment by maysamrasoli** [comment]
درور
مشکل از پروژه بنده بود.
از ریسورس های قبلی مقدار 
    <integer name="google_play_services_version">4242000</integer>

به اشتباه مونده بود. و همکارم متوجه نشده بود.
پاک کردیم درست شد.
ممنون و موفق باشید.
