### ISSUE TITLE
 E/Pushe: Exception caught 

### ISSUE THREAD

**Issue by maysamrasoli** [pusheco/android-studio-sample#4]
سلام دوستان
اطلاع دارید این خطا از چی هستش؟

04-03 17:05:49.870 7669-8726/ir.category_manager D/Pushe: Exception caught 1
04-03 17:05:49.870 7669-8726/ir.category_manager E/Pushe: Exception caught 
                                                          java.lang.NumberFormatException: Invalid int: "null"
                                                              at java.lang.Integer.invalidInt(Integer.java:138)
                                                              at java.lang.Integer.parse(Integer.java:410)
                                                              at java.lang.Integer.parseInt(Integer.java:367)
                                                              at java.lang.Integer.parseInt(Integer.java:334)
                                                              at com.a.a.d.run(Unknown Source)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                              at java.lang.Thread.run(Thread.java:818)
04-03 17:05:49.873 7669-8726/ir.category_manager W/GooglePlayServicesUtil: Google Play services out of date.  Requires 10084000 but found 8489470
04-03 17:05:49.874 7669-8726/ir.category_manager W/GooglePlayServicesUtil: Google Play services out of date.  Requires 10084000 but found 8489470
04-03 17:05:49.875 7669-8726/ir.category_manager E/AndroidRuntime: FATAL EXCEPTION: Sentry HTTP Thread 1
                                                                   Process: ir.category_manager, PID: 7669
                                                                   java.lang.NumberFormatException: Invalid int: "null"
                                                                       at java.lang.Integer.invalidInt(Integer.java:138)
                                                                       at java.lang.Integer.parse(Integer.java:410)
                                                                       at java.lang.Integer.parseInt(Integer.java:367)
                                                                       at java.lang.Integer.parseInt(Integer.java:334)
                                                                       at com.a.a.d.run(Unknown Source)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
04-03 17:05:49.947 7669-7696/ir.category_manager E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa1414730

**Comment by akramShokri** [comment]
سلام
خیر، خطا مربوط به کتابخانه پوشه نیست.
با توجه به اینکه شما خطاهای پروژه خودتان را در این پروژه که یک نمونه برنامه است ریپورت می کنید و این به مفهوم 
issue reporting
که در گیت هاب هست تناسبی ندارد، لطفا بعد از این خطاهای مرتبط با  **این پروژه** را در اینجا ریپورت کنید. همانطور که می دانید کتابخانه پوشه متن باز نیست و اگر با مشکل یا خطایی در استفاده از کتابخانه مواجه هستید، روش درست استفاده از سیستم پشتیبانی سایت پوشه است.
